---
- name: Filter in List by Values
  hosts: all
  gather_facts: true
  tasks:
    - name: all features
      ansible.builtin.debug:
        var: 'ansible_eth1.features'

    - name: filter features
      ansible.builtin.debug:
        msg: "{{ (ansible_eth1.features | dict2items | selectattr('key', 'match', 'rx_vlan_offload')) }}"
...
