---
- name: date and time
  hosts: all
  gather_facts: true
  tasks:
    - name: date and time
      ansible.builtin.debug:
        var: ansible_date_time

    - name: ISO8601 format date
      ansible.builtin.debug:
        var: ansible_date_time.date
...

